apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: aux
spec:
  type: NodePort
  selector:
    app: hive-metastore
  ports:
    - protocol: TCP
      port: 9083
      targetPort: 9083